name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Build Release
      run: dotnet build --configuration Release src/VCDiff.sln
    - name: Build Debug
      run: dotnet build --configuration Debug src/VCDiff.sln
    - name: Run Tests
      run: dotnet test src/VCDiff.sln
    
